using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace JadaraITKnowledgeSystem.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddQuizGenerationFeature : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "PartNumber",
                table: "Quizzes",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Source",
                table: "Quizzes",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "SourceMaterialId",
                table: "Quizzes",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "TotalParts",
                table: "Quizzes",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AutoGeneratedQuizCount",
                table: "CourseMaterials",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "HasGeneratedQuizzes",
                table: "CourseMaterials",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "QuizGenerationJobs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    MaterialId = table.Column<int>(type: "int", nullable: false),
                    CourseId = table.Column<int>(type: "int", nullable: false),
                    RequestedByUserId = table.Column<int>(type: "int", nullable: false),
                    Status = table.Column<int>(type: "int", nullable: false),
                    ErrorMessage = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    GeneratedQuizCount = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    GeneratedQuizIds = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Options = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: false),
                    CompletedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_QuizGenerationJobs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_QuizGenerationJobs_CourseMaterials_MaterialId",
                        column: x => x.MaterialId,
                        principalTable: "CourseMaterials",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_QuizGenerationJobs_Courses_CourseId",
                        column: x => x.CourseId,
                        principalTable: "Courses",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_QuizGenerationJobs_Users_RequestedByUserId",
                        column: x => x.RequestedByUserId,
                        principalTable: "Users",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "SystemSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Key = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Value = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    IsEnabled = table.Column<bool>(type: "bit", nullable: false, defaultValue: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SystemSettings", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "SystemSettings",
                columns: new[] { "Id", "CreatedAt", "CreatedBy", "Description", "IsEnabled", "Key", "UpdatedAt", "UpdatedBy", "Value" },
                values: new object[,]
                {
                    { 1, new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "System", "Enable AI-powered quiz generation from course materials", true, "Features.QuizGeneration.Enabled", null, null, "true" },
                    { 2, new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "System", "Maximum concurrent quiz generation jobs", true, "Features.QuizGeneration.MaxConcurrent", null, null, "3" },
                    { 3, new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "System", "Default number of questions per generated quiz", true, "Features.QuizGeneration.DefaultQuestions", null, null, "8" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Quizzes_Source",
                table: "Quizzes",
                column: "Source");

            migrationBuilder.CreateIndex(
                name: "IX_Quizzes_SourceMaterialId",
                table: "Quizzes",
                column: "SourceMaterialId");

            migrationBuilder.CreateIndex(
                name: "IX_CourseMaterials_HasGeneratedQuizzes",
                table: "CourseMaterials",
                column: "HasGeneratedQuizzes");

            migrationBuilder.CreateIndex(
                name: "IX_QuizGenerationJobs_CourseId",
                table: "QuizGenerationJobs",
                column: "CourseId");

            migrationBuilder.CreateIndex(
                name: "IX_QuizGenerationJobs_CreatedAt",
                table: "QuizGenerationJobs",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_QuizGenerationJobs_MaterialId",
                table: "QuizGenerationJobs",
                column: "MaterialId");

            migrationBuilder.CreateIndex(
                name: "IX_QuizGenerationJobs_RequestedByUserId",
                table: "QuizGenerationJobs",
                column: "RequestedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_QuizGenerationJobs_Status",
                table: "QuizGenerationJobs",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_SystemSettings_Key",
                table: "SystemSettings",
                column: "Key",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Quizzes_CourseMaterials_SourceMaterialId",
                table: "Quizzes",
                column: "SourceMaterialId",
                principalTable: "CourseMaterials",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Quizzes_CourseMaterials_SourceMaterialId",
                table: "Quizzes");

            migrationBuilder.DropTable(
                name: "QuizGenerationJobs");

            migrationBuilder.DropTable(
                name: "SystemSettings");

            migrationBuilder.DropIndex(
                name: "IX_Quizzes_Source",
                table: "Quizzes");

            migrationBuilder.DropIndex(
                name: "IX_Quizzes_SourceMaterialId",
                table: "Quizzes");

            migrationBuilder.DropIndex(
                name: "IX_CourseMaterials_HasGeneratedQuizzes",
                table: "CourseMaterials");

            migrationBuilder.DropColumn(
                name: "PartNumber",
                table: "Quizzes");

            migrationBuilder.DropColumn(
                name: "Source",
                table: "Quizzes");

            migrationBuilder.DropColumn(
                name: "SourceMaterialId",
                table: "Quizzes");

            migrationBuilder.DropColumn(
                name: "TotalParts",
                table: "Quizzes");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedQuizCount",
                table: "CourseMaterials");

            migrationBuilder.DropColumn(
                name: "HasGeneratedQuizzes",
                table: "CourseMaterials");
        }
    }
}
