using JadaraITKnowledgeSystem.Application.Common.Validators;

namespace JadaraITKnowledgeSystem.Application.Features.Courses.Queries.GetEnrolledCourses;

public sealed class GetEnrolledCoursesQueryValidator : PaginatedRequestValidator<GetEnrolledCoursesQuery>;
