using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using JadaraITKnowledgeSystem.Domain.Courses.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace JadaraITKnowledgeSystem.Infrastructure.Persistence.Configurations
{
    internal class CourseMaterialConfiguration : IEntityTypeConfiguration<CourseMaterial>
    {
        public void Configure(EntityTypeBuilder<CourseMaterial> builder)
        {
            builder.ToTable("CourseMaterials");
            builder.HasKey(m => m.Id);

            builder.Property(m => m.Title)
                   .IsRequired()
                   .HasMaxLength(250);

            builder.Property(m => m.ContentUrl)
                   .IsRequired()
                   .HasMaxLength(500);

            builder.Property(m => m.Description)
                   .HasMaxLength(500)
                   .IsRequired(false);

            builder.Property(m => m.HasGeneratedQuizzes)
                   .IsRequired()
                   .HasDefaultValue(false);

            builder.Property(m => m.AutoGeneratedQuizCount)
                   .IsRequired()
                   .HasDefaultValue(0);

            var tagsComparer = new ValueComparer<List<string>>(
                (c1, c2) => c1.SequenceEqual(c2, StringComparer.OrdinalIgnoreCase),
                c => c.Aggregate(0, (a, v) => HashCode.Combine(a, StringComparer.OrdinalIgnoreCase.GetHashCode(v))),
                c => c.ToList());

            builder.Property<List<string>>("_tags")
                   .HasField("_tags")
                   .UsePropertyAccessMode(PropertyAccessMode.Field)
                   .HasColumnName("Tags")
                   .HasColumnType("nvarchar(max)")
                   .HasConversion(
                       v => JsonSerializer.Serialize(v, (JsonSerializerOptions?)null),
                       v => string.IsNullOrWhiteSpace(v)
                            ? new List<string>()
                            : JsonSerializer.Deserialize<List<string>>(v, (JsonSerializerOptions?)null) ?? new List<string>())
                   .Metadata.SetValueComparer(tagsComparer);

            // Auditable fields
            builder.Property(m => m.CreatedAt)
                   .IsRequired();

            builder.Property(m => m.CreatedBy)
                   .HasMaxLength(100)
                   .IsRequired(false);

            builder.Property(m => m.UpdatedAt)
                   .IsRequired(false);

            builder.Property(m => m.UpdatedBy)
                   .HasMaxLength(100)
                   .IsRequired(false);

            // Relationships
            builder.HasOne(m => m.Course)
                   .WithMany(c => c.Materials)
                   .HasForeignKey(m => m.CourseId)
                   .OnDelete(DeleteBehavior.Cascade);

            builder.HasOne(m => m.Folder)
                   .WithMany(f => f.Materials)
                   .HasForeignKey(m => m.FolderId)
                   .OnDelete(DeleteBehavior.Restrict);

            // Indexes to optimize lookups
            builder.HasIndex(m => m.CourseId);
            builder.HasIndex(m => new { m.CourseId, m.FolderId });
            builder.HasIndex(m => m.HasGeneratedQuizzes);
        }
    }
}
